### ISSUE TITLE
Reduce `Cannot decrypt cookie value, create a new fresh session` error in terminal

### ISSUE THREAD

**Issue by liusida** [liusida/ComfyUI-Login#8]
`Cannot decrypt cookie value, create a new fresh session` is caused by the browser trying to connect the new server, but new server has a new key for encryption.

Please solve it.

**Comment by liusida** [comment]
fixed

**Comment by agarzon-orangerine** [comment]
Well, is still happening. already reinstalled the node, delete the login folder and deleted the .secret-key.txt and restarted the service

 
![image](https://github.com/user-attachments/assets/85485329-a930-4f03-a49e-1db56daf1b39)

**Comment by liusida** [comment]
I guess this happens because the server has been restarted and expecting a new secret key, but the client (the browser) still in the old session, and using the old secret key. If this is true, pressing Ctrl+F5 in browser can stop this issue. Would you like to try?

**Comment by wujohns** [comment]
> I guess this happens because the server has been restarted and expecting a new secret key, but the client (the browser) still in the old session, and using the old secret key. If this is true, pressing Ctrl+F5 in browser can stop this issue. Would you like to try?

But I use comfyui in pure server api mode, there is no way to use browser to refresh it...
